name: ScottCI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install xcpretty
        run: |
          sudo gem install xcpretty

      - name: Install dependencies if needed
        run: |
          if [ -f Package.swift ]; then
            swift package update
          fi

          if [ -f Podfile ]; then
            sudo gem install cocoapods
            pod install
          fi

      - name: Run tests
        run: |
          xcodebuild test | xcpretty --format gcov

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
